# Generated by Django 2.1.4 on 2020-10-21 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contas', '0002_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='contas.Conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacao',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.TextField(),
        ),
    ]
